### ISSUE TITLE
Update maven poms to current system used by app accelerator

### ISSUE THREAD

**Issue by ebullient** [gameontext/gameon-room-java#15]
Specifically mvn install should no longer start the server, etc.

**Comment by ebullient** [comment]
@katheris -- do we still need to do this? covered elsewhere?

**Comment by katheris** [comment]
@ebullient I think this issue is a bit muddled and not specific enough, the title is to match it up to app accelerator, but then we say we specifically want to set it up so that mvn install doesn't start the server, which currently the app accelerator code does (although we may decide to change that..). Also the maven code has been updated to not start the server as part of pull request #24 . Probably makes more sense to close this issue and open a new one if there are more things about the maven code that we want to change.
